Start remote functionality

diff --git a/usr b/usr
--- a/usr
+++ b/usr
@@ -4,8 +4,9 @@ set -e
 
 : "${USR_DIR:=$HOME/src/git/usr}"
 
+mkdir -p "$USR_DIR"/var
+mkdir -p "$USR_DIR"/home
 mkdir -p "$USR_DIR"/modules
-mkdir -p "$USR_DIR"/installed
 
 die() {
 	>&2 printf "%s\n" "$*"
@@ -13,13 +14,13 @@ die() {
 }
 
 usage() {
-	die "usage: usr [-a <module>] [-r <module>] [-i <module>] [-l]"
+	die "usage: usr [-a <module>] | [-r <module>] | [-i <module>] | [-u] | [-l[i | r]]"
 }
 
 module_add() {
 	MOD="$2"
 	MOD_FILE="$USR_DIR/modules/$MOD".mod.sh
-	MOD_INSTALL="$USR_DIR/installed/$MOD"
+	MOD_INSTALL="$USR_DIR/var/$MOD".installed
 
 	[ -e "$MOD_INSTALL" ] && die "$MOD is already installed"
 	[ -z "$MOD" ] && usage
@@ -35,7 +36,7 @@ module_add() {
 module_remove() {
 	MOD="$2"
 	MOD_FILE="$USR_DIR/modules/$MOD".mod.sh
-	MOD_INSTALL="$USR_DIR/installed/$MOD"
+	MOD_INSTALL="$USR_DIR/var/$MOD".installed
 
 	[ -e "$MOD_INSTALL" ] || die "$MOD is not installed"
 	[ -z "$MOD" ] && usage
@@ -62,9 +63,36 @@ module_info() {
 
 list_modules() {
 	for MOD in "$USR_DIR"/modules/*; do 
-		[ -f "$MOD" ] && printf "%s\n" "$MOD"
+		if [ -f "$MOD" ] ; then
+			if [ "${MOD#*.}" = "mod.sh" ] ; then
+				NODOT=${MOD%%.*}
+				printf "%s\n" "${NODOT##*/}"
+			fi
+		fi
 	done
 }
+
+list_installed() {
+	for MOD in "$USR_DIR"/var/*; do 
+		if [ -f "$MOD" ] ; then
+			if [ "${MOD#*.}" = "installed" ] ; then
+				NODOT=${MOD%%.*}
+				printf "%s\n" "${NODOT##*/}"
+			fi
+		fi
+	done
+}
+
+list_remote() {
+	xargs printf "%s" <"$USR_DIR"/var/remote.list
+}
+
+update_remote() {
+	xargs printf "url = %smod.list" <"$USR_DIR"/var/remote | curl -sLf -o "$USR_DIR"/var/remote.list -K - || die "error updating"
+}
+
+[ -e "$USR_DIR"/modules/mod.list ] || list_modules > "$USR_DIR"/modules/mod.list
+[ -e "$USR_DIR"/var/remote ] || printf "https://raw.githubusercontent.com/tteeoo/usr/main/modules/" > "$USR_DIR"/var/remote
 
 case ${1#-} in
 	h) usage ;;
@@ -72,6 +100,9 @@ case ${1#-} in
 	r) module_remove "$@" ;;
 	i) module_info "$@" ;;
 	l) list_modules ;;
+	u) update_remote ;;
+	li) list_installed ;;
+	lr) list_remote ;;
 	*) usage ;;
 esac
 
